### ISSUE TITLE
[attribute-string-redundant] Not consider when ares used uppercase

### ISSUE THREAD

**Issue by luistorresm** [OCA/pylint-odoo#108]
In some cases the label of fields must be in uppercases, but the Odoo label is:

First letter upper and and the others in lower.
![captura de pantalla 2017 01 23 a la s 16 33 36](https://cloud.githubusercontent.com/assets/7606656/22226169/def57e62-e18a-11e6-8aac-649502e7b976.png)

Could we omit this validation?

**Comment by moylop260** [comment]
@JesusZapata 
Could you help us to fix it?

FYI the valide cases are:
 1. Capitalize Case (v8, v9 y v10)
 2. Title case (master)

**Comment by moylop260** [comment]
Fixed from https://github.com/vauxoo-dev/pylint-odoo/commit/a8a0dc3c4597386b0859ced5d2ed174539b9e909
