### ISSUE TITLE
Can not disable messages from `odoolint`

### ISSUE THREAD

**Issue by a-da** [OCA/pylint-odoo#111]
I tried command line and .pylintrc, both does not disable messages

	~
	pylint --reports=n --load-plugins=pylint_odoo -e odoolint my_odoo_module/configurations.py
	************* Module  my_odoo_module.configurations
	C:  1, 0: No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-` (no-utf8-coding-comment)
	W: 21, 0: Statement seems to have no effect (pointless-statement)
	~
	$ pylint --disable=pointless-statement --reports=n --load-plugins=pylint_odoo -e odoolint my_odoo_module/configurations.py
	************* Module  my_odoo_module.configurations
	C:  1, 0: No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-` (no-utf8-coding-comment)
	~
	$ pylint --disable=no-utf8-coding-comment --reports=n --load-plugins=pylint_odoo -e odoolint my_odoo_module/configurations.py
	************* Module  my_odoo_module.configurations
	C:  1, 0: No UTF-8 coding comment found: Use `# coding: utf-8` or `# -*- coding: utf-8 -*-` (no-utf8-coding-comment)
	W: 21, 0: Statement seems to have no effect (pointless-statement)

**Comment by moylop260** [comment]
Try using disable parameter after enable one
I mean,
`pylint  --reports=n --load-plugins=pylint_odoo -e odoolint -d no-utf8-coding-comment my_odoo_module/configurations.py`

**Comment by a-da** [comment]
It's  working !!, Thanks @moylop260 

Filling the gaps from documentation, about `.pylintrc` in `pylint-odoo`, for usage

cat .pylintrc
 
	[Master]
	init-hook='sys.path.append("/home/ada/github.com/odoo-dev")'
	load-plugins=pylint_odoo

	[MESSAGES CONTROL]
	enable=odoolint
	disable=no-utf8-coding-comment

now its run perfectly

       pylint  --reports=n  real_estate/configurations.py
