### ISSUE TITLE
Consider adding a Check for return of public methods

### ISSUE THREAD

**Issue by gdgellatly** [OCA/pylint-odoo#123]
In response to this https://github.com/odoo/odoo/pull/16538

It seems that if public methods do not return a value, xmlrpc breaks when called.

**Comment by rvalyi** [comment]
None return values (often implicit) does indeed break most of XMLRPC clients (specially the Java one for instance) as null values aren`t part of the strict XMLRPC spec but are eventually brought by an extension that is implemented or not depending on your XMLRPC client https://web.archive.org/web/20050911054235/http://ontosys.com/xml-rpc/extensions.php

That being said, these days Odoo has a decent JSON endpoint and it`s probably debatable how much care should be taken with the old XMLRPC protocol...

**Comment by dreispt** [comment]
> it`s probably debatable how much care should be taken with the old XMLRPC protocol...

AFAIK XMLRPC is still officially supported, so we should ensure that it works.

**Comment by moylop260** [comment]
Closing because of last comment.
