### ISSUE TITLE
Check if a file called in __manifest__.py exists in the filesystem

### ISSUE THREAD

**Issue by ebirbe** [OCA/pylint-odoo#124]
Hello, I recently had an error while building a custom module:

![17132811017-skortkefvw jpg](https://cloud.githubusercontent.com/assets/442938/25256970/aaccfe1e-2602-11e7-98af-b19f17ecd2bf.png)

This error was caused because I deleted the unnecessary file from module's folder, but I forgot to remove it from the `__manifest__.py` file.

Could be possible `pylint-odoo` make that check to `data` and `demo` elements declared into modules manifest, to avoid this kind of errors?

**Comment by moylop260** [comment]
@JesusZapata 
Could you help us with this check?
