### ISSUE TITLE
W7907 	%s Duplicate xml field "%s" in lines %s 	duplicate-xml-fields

### ISSUE THREAD

**Issue by gdgellatly** [OCA/pylint-odoo#125]
This error should be reduced to informational or ignored in demo data xml files.  It is entirely legitimate and occasionally necessary to have duplicate xml-ids,  even if 99% of the time it is an error.  

Sometimes, such as when dealing with products, product templates and attributes you need to create circular references in order to trigger ORM create functions correctly and get around required fields of each model.

**Comment by pedrobaeza** [comment]
This issue should be put in MQT, not here. Here it's the code that detects the duplication, but it's enabled on https://github.com/OCA/maintainer-quality-tools/tree/master/travis/cfg.

Anyway, are you sure is a blocking error, or it's only a warning?

**Comment by gdgellatly** [comment]
Its blocking in the sense it turns travis red and you may as well give up
at that point.

**Comment by pedrobaeza** [comment]
OK, @moylop260 can tell here.

**Comment by moylop260** [comment]
Hello @gdgellatly 
Thanks for issue.

Do you have the real PR with this valid case, please?
(I need use it as example in order to skip it)

**Comment by gdgellatly** [comment]
Hi,

https://github.com/OCA/product-attribute/pull/255/files#diff-62acad6fab5a7904003f07e6ca6a5dd6

It will be this file in this PR.  Currently, just to get travis green I've commented out the circular reference lines and then create the variants in the tests.  I've been force pushing this repo so I'll update it later today with a proper commit with the demo data uncommented and no longer creating variants in test setup.

The problem occurs because attribute lines requires a product template.  But product template requires attribute lines to be written on the template in order to generate variants. Therefore you need to declare a template, create attribute lines referring to that template, then assign the attribute lines to the template in order for the variants to be created.

**Comment by moylop260** [comment]
Could you push 2 commits, please?
- First commit with the error `duplicate-xml-fields`
- Second commit with the fix for `duplicate-xml-fields`

**Comment by gdgellatly** [comment]
OK I have pushed 3 commits

https://github.com/OCA/product-attribute/pull/255/commits/7c7a5e14d0ffde5fcb23200b6dc403e63368b440 error
https://github.com/OCA/product-attribute/pull/255/commits/01ef5615b0589fbc6df3b2e09989b6394ebfe474 with fix, but creates new error
https://github.com/OCA/product-attribute/pull/255/commits/06cdf0e525b04a8da5ad545865b9abfdcfc635fc possible workaround - it may be that we just stick with the workaround if it passes as it is a pretty rare case the legitimate use of duplicate ids.

**Comment by gdgellatly** [comment]
@moylop260 OK the workaround works which was just creating a second xml file.  Maybe we just stick with that as the workaround.  If you need duplicate xml-ids you need to use one file per reference.

/cc @pedrobaeza

**Comment by gdgellatly** [comment]
I don't think this is an issue anymore.
