### ISSUE TITLE
How to disable file-not-used warning for specific file

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/pylint-odoo#133]
Hello,

I have a module which contains SQL script (module/script/script.sql) that are loaded directly from python code. With this case, the warning disable file-not-used is raised. Is it possible to ignore this one locally ?

Thanks,

Adrien

**Comment by pedrobaeza** [comment]
You can put the file on one of these folders for avoiding the warning: static, test and tests.

Reference: https://github.com/OCA/pylint-odoo/blob/8377b02038b6eb50d40bea9f7da99398fffc4fd3/pylint_odoo/checkers/modules_odoo.py#L752

**Comment by adrienpeiffer** [comment]
Ok static should make the job. Thanks !
