### ISSUE TITLE
RFQ - [REF] missing-newline-extrafiles: Consider more extra files

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#134]
Currently we have the check missing-newline-extrafiles for all extra files.
But for less and svg extra files is not emitted.

So we need to consider them like as external files just for this check.

**Comment by pedrobaeza** [comment]
SVG files are generated through other applications (like Inkscape), so they should be left out as we have no control over the file written.

**Comment by moylop260** [comment]
superseded by https://github.com/OCA/pylint-odoo/issues/267
