### ISSUE TITLE
Detect default bad assignment 

### ISSUE THREAD

**Issue by a-da** [OCA/pylint-odoo#139]
for example

   # bad 
   start_date = fields.Date(string='Start Date', default=date.today().strftime('%Y-%m-%d'))

   # good
   start_date = fields.Date(string='Start Date', default=fields.Date.today)

**Comment by moylop260** [comment]
:+1:
In fact, we should emit a lint if a strftime defined as global variable in odoo.tools is used directly with '%Y... instead of use the global variable

**Comment by moylop260** [comment]
Closing since that anybody is working on this new check.
feel free of re-open it if you have a new PR to do it.
