### ISSUE TITLE
odoo-pylint install issue: No module named tasks

### ISSUE THREAD

**Issue by jcdrubay** [OCA/pylint-odoo#144]
I managed to install odoo-pylint in my local, but I can't install it on a server.

### Environment where it does works (on a server):

- Ubuntu 16.04.3 LTS
- nodejs: v6.11.2
- setuptools 36.2.7 from /usr/local/lib/python2.7/dist-packages (Python 2.7)
- pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
- pbr 3.0.0
- pylint==1.6.4
- pylint-plugin-utils==0.2.4
- npm eslint --version # 3.10.10

### Environment where it works (in my local):

- Ubuntu 16.04.3 LTS
- nodejs: v6.11.2
- setuptools 36.2.7 from /usr/local/lib/python2.7/dist-packages (Python 2.7)
- pip 9.0.1
- pbr 3.0.0
- pylint==1.6.4
- pylint-plugin-utils==0.2.4
- npm eslint --version # 3.10.10
- pylint-odoo==1.8.1.dev4

I face the same error with both installation commands
- `pip install --upgrade --pre pylint-odoo`
- `pip install --upgrade git+https://github.com/oca/pylint-odoo.git`

Finally, I tried to install from the source and get the same error:

```
╰─➤ sudo pip install -e . 
The directory '/home/myuser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. The directory '/home/myuser/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Obtaining file:///home/myuser/git-pylint-odoo/pylint-odoo 

Complete output from command python setup.py egg_info: 
ERROR:root:Error parsing 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr 
attrs = util.cfg_to_args(path, dist.script_args) 
File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 267, in cfg_to_args wrap_commands(kwargs) 
File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 569, in wrap_commands cmdclass = ep.resolve() 
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) 
ImportError: No module named tasks 
error in setup command: Error parsing /home/myuser/git-pylint-odoo/pylint-odoo/setup.cfg: ImportError: No module named tasks ---------------------------------------- Command "python setup.py egg_info" failed with error code 1 in /home/myuser/git-pylint-odoo/pylint-odoo/ 
```

Thanks in advance for your help :)

**Comment by moylop260** [comment]
Thanks for reporting issue.

I have created the following Dockerfile:

```Dockerfile
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y python-pip nodejs npm git && \
    pip install -U pip && \
    pip install -U setuptools pylint==1.6.4 pylint-plugin-utils==0.2.4 pbr && \
    npm install eslint
RUN pip install --upgrade --pre pylint-odoo
RUN pip install --upgrade git+https://github.com/oca/pylint-odoo.git
```

Running the following command to build the image: `docker build -t pylint_error .` I have the following result:

 - <img width="1280" alt="screen shot 2017-08-11 at 23 34 16" src="https://user-images.githubusercontent.com/6644187/29237796-7ba95294-7eeb-11e7-86e3-fc69938574ac.png">

I can't reproduce it
Could you help me to detect where I'm wrong?

You can clean you local installation running the following commands:
```bash
sudo pip uninstall pylint pylint-odoo pylint-plugin-utils astroid
pip uninstall pylint pylint-odoo pylint-plugin-utils astroid
```
Notice the `sudo` and notice the double execution too in order to clean local user environment and global environment..

And install again using:
`pip install --upgrade --no-cache-dir pylint-odoo`
Notice the `--no-cache-dir`

In other extreme way you could use a `virtualenv`:
`pip install -U virtualenv && virtualenv ~/.pylint_env && ~/.pylint_env/bin/activate && pip install pylint-odoo`

**Comment by jcdrubay** [comment]
@moylop260 thanks for your perfect and quick answer.

I did the double uninstall and and the re-install with no-cache-dir and still no luck.

This issue is strange because I did setup successfully in many other hosts and only this one has the problem now. This particular host having production running, I don't want to mess up too much with it by uninstalling / reinstalling too many things. Since it's production, I really don't need odoo-pylint on that host either. So I guess I will stop here for now.

What I imagine is that some package has been installed differently on that host compare to other host which is strange because the setup is mostly automated.

Thanks again for your time and great support. If I can find the explanation at some point I will update the issue.

In the meantime I think it is better to close the issue.

**Comment by moylop260** [comment]
ok

Could you send me the result of 'pip freeze' command and the packages python-* installed from apt-get?

**Comment by jcdrubay** [comment]
Thanks @moylop260 for pushing me with your kind support. :)

I compared all pip and apt packages and finally found the guilty one: `cli-helpers `. After uninstalling that package, I could successfully odoo-pylint.

 `cli-helpers` was installed when I installed `pgcli`.

```
╰─➤  pipdeptree -r -p cli-helpers
cli-helpers==0.2.3
  - pgcli==1.7.0 [requires: cli-helpers<1.0.0,>=0.2.0]
```

Note that I did not face this problem on other environments as they were installed long time ago with `cli-helpers==0.1.0`.

Let me know if you want me to do anything else, but fixing that issue seem quite tough for me.

To be fair and square, here is the Dockerfile to reproduce the issue :)

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y python-pip nodejs npm git && \
    pip install -U pip && \
    pip install -U setuptools pylint==1.6.4 pylint-plugin-utils==0.2.4 pbr==3.0.0 && \
    npm install eslint
RUN pip install cli-helpers
RUN pip install --upgrade --pre pylint-odoo
RUN pip install --upgrade git+https://github.com/oca/pylint-odoo.git
```

**Comment by moylop260** [comment]
It looks like as [pbr](https://docs.openstack.org/pbr) issue using cli-helpers because using a basic configuration package:

```bash
git init my_pack && cd my_pack
echo """[metadata]
name = foo
author = bar
author_email = foo@bar""" > setup.cfg

echo """import setuptools
setuptools.setup(setup_requires=['pbr'], pbr=True)
""" > setup.py
git add setup.cfg setup.py && git commit -m "foo"
python setup.py install
```

And you will have the same error.
Maybe you should create a issue from pbr package

**Comment by jcdrubay** [comment]
Question asked https://ask.openstack.org/en/question/109649/pbr-issue-when-installing-a-package-possibly-due-to-pbr-incompatibility-with-cli-helpers020/

Now in the moderation queue.

**Comment by mapuerta** [comment]
Hi @moylop260 @jcdrubay  

i resolved this problem, deleted file `entry_points.txt` in folder cli_helpers-0.2.3.dist-info 

Here is the Dockerfile with change mentioned

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y python-pip nodejs npm git && \
    pip install -U pip && \
    pip install -U setuptools pylint==1.6.4 pylint-plugin-utils==0.2.4 pbr==3.0.0 && \
    npm install eslint
RUN pip install cli-helpers
RUN rm -rf  /usr/local/lib/python2.7/dist-packages/cli_helpers-0.2.3.dist-info/entry_points.txt
RUN pip install --upgrade --pre pylint-odoo
RUN pip install --upgrade git+https://github.com/oca/pylint-odoo.git
```

Here [video](https://asciinema.org/a/gqEuZsUtleLuDcC5IR41YOfEo) with debugging of build of image
