### ISSUE TITLE
[RFC] Deprecated <tree> attributes

### ISSUE THREAD

**Issue by naglis** [OCA/pylint-odoo#146]
`string` attribute in `<tree>` node is [deprecated since 8.0](https://github.com/odoo/odoo/blob/420e433fa3a6b671868fa578e6006dd215570706/doc/reference/views.rst#lists) (no longer displayed) and `colors` and `fonts` are [deprecated since 9.0](https://github.com/odoo/odoo/blob/420e433fa3a6b671868fa578e6006dd215570706/doc/reference/views.rst#lists) in favor of `decoration-{$name}`.

I went ahead an implemented a crude version of it, however, there is the question if something like this would likely be integrated into _pylint-odoo_?

If yes, then I have a few further questions:

1. Since the rule deals with certain versions of Odoo only, the check should be skipped in other versions in order to avoid false positives. I saw [`valid_odoo_versions` config value being used](https://github.com/OCA/pylint-odoo/blob/d0b0d100057666f21bbb7b84c1779e2c02ca8c80/pylint_odoo/checkers/modules_odoo.py#L770-L771) in one place. Is this a good/right approach?
2. What is the policy for comming up with new message codes? Do I simply increment the highest existing code by one?

**Comment by moylop260** [comment]
> valid_odoo_version

That approach looks good to me.
We will avoid use one pylint configuration file for each odoo version and will avoid many false positives/negatives if you don't have a specified configuration file.

> Do I simply increment the highest existing code by one?

There is not a policy. Just not duplicated and not WIP code used from PR.
