### ISSUE TITLE
[RFC] Tighten valid module version check

### ISSUE THREAD

**Issue by naglis** [OCA/pylint-odoo#152]
Currently, the following module versions will be considered as valid by _pylint-odoo_ when using default configuration:

- `10+0.1.0.0`, because the dot from `valid_odoo_versions` is not escaped when building the valid module version pattern (and the `.` inside a regex matches any character other than a newline): https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L657-L661
- `10.0.1.0.0WHATEVER`, because `re.match` [is used](https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L661) inside `formatversion()`, which [matches the string from the beginning](https://docs.python.org/2/library/re.html#re.match), however, there is no `$` at the end of the default value for `manifest_version_format` to match the end of the string: https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L237
Thus, anything can follow once the version is matched from the beginning of the string.

I have started working on a fix, however, I have stumbled into a slight problem for which I need feedback from the authors - if a _.pylintrc_ file is used with `manifest_version_format` defined inside it using the `%(valid_odoo_versions)s` placeholder, then `manifest_version_format` will be set automatically by `ConfigParser` (which [pylint uses for configuration parsing](https://github.com/PyCQA/pylint/blob/e231a409a83a23c24c8b7dbbaca79314eee6d4c6/pylint/config.py#L462)) due to [interpolation](https://docs.python.org/2/library/configparser.html#ConfigParser.ConfigParser). This means that at the point when the `manifest_version_format_parsed` string is built: https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L657-L661
then `self.config.manifest_version_format` no longer contains the `%(valid_odoo_versions)s` placeholder, as it was already formatted by `ConfigParser`. This becomes a problem if we want to escape the dots from `valid_odoo_versions` (eg. `10.0` -> `10\.0`) inside [`formatversion()`](https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L657), as our values will be simply ignored if a config file is used with `manifest_version_format` defined inside it using the `%(valid_odoo_versions)s` placeholder.

I have comeup with one solution - switch to [`str.format()`](https://docs.python.org/2/library/stdtypes.html#str.format) style formatting for `manifest_version_format` in the config, which would allow to avoid interpolation by `ConfigParser`. However, I guess it would be a breaking change. So my question is - would it be ok?

Maybe someone has other suggestions?

**Comment by moylop260** [comment]
We have a guideline from [CONTRIBUTING.md#idioms](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#idioms):
 - `Prefer % over .format(), prefer %(varname) instead of positional. This is better for translation and clarity.`

And we had issues related with this method in the past related with:
 - ![screen shot 2017-09-04 at 11 23 10](https://user-images.githubusercontent.com/6644187/30033509-4b3f4630-9161-11e7-9bc1-9215e6108fbe.png)

E.g. https://github.com/OCA/manufacture/issues/146

Maybe for pylint is not a real issue but we prefer to follow the same odoo guidelines here too.

What is the wrong with binop (%) vs format here?

**Comment by moylop260** [comment]
I have created the following fix: https://github.com/OCA/pylint-odoo/pull/153
Could you check it, please?

**Comment by naglis** [comment]
> What is the wrong with binop (%) vs format here?

The problem is that the `%()s` placeholders are automaticaly formated by `ConfigParser` (due to interpolation). Thus, if a _.pylintrc file_ is used with `manifest_version_format` defined inside it using the `%(valid_odoo_versions)s` placeholder these lines have no effect:
https://github.com/OCA/pylint-odoo/blob/a14ddca6f0d57e603c55f60b0128b129ad5fb81e/pylint_odoo/checkers/no_modules.py#L658-L660
