### ISSUE TITLE
No Changelog available for version > 1.8.0

### ISSUE THREAD

**Issue by katyukha** [OCA/pylint-odoo#179]
Hello!

There is no changelog available for versions > 1.8.0
And readme is not parsed by pypi

See:
- [1.8.0](https://pypi.python.org/pypi/pylint-odoo/1.8.0): Changelog present
- [1.8.1](https://pypi.python.org/pypi/pylint-odoo/1.8.1): No changelog
- [1.8.2](https://pypi.python.org/pypi/pylint-odoo/1.8.2): No changelog
- [1.9.3](https://pypi.python.org/pypi/pylint-odoo/1.9.3): No changelog
- [last](https://pypi.python.org/pypi/pylint-odoo/): No changelog

**Comment by moylop260** [comment]
The README was fixed but the Changelog is not present yet... (WIP)

**Comment by moylop260** [comment]
Fixing from https://github.com/OCA/pylint-odoo/commit/7829e215cc40df3ac63fe5ded05b17f54740f5de released from [1.9.5](https://pypi.org/project/pylint-odoo/1.9.5/)

Adding `skip_cleanup: true` to .travis.yml 

Thanks!
