### ISSUE TITLE
should files in /examples be ignored?

### ISSUE THREAD

**Issue by hbrunn** [OCA/pylint-odoo#193]
sorry, no time to read the code currently, but I dump this here as a reminder: The readme states that files in `examples` should be ignored, is that the case? And is https://travis-ci.org/OCA/runbot-addons/jobs/374474881#L715 a bug then that I should PR to fix?

**Comment by pedrobaeza** [comment]
I think this should be in OCA/maintainer-quality-tools. It's there where the logic about what to check is.

**Comment by hbrunn** [comment]
https://github.com/OCA/pylint-odoo/blob/eca45f3176c9d17d8764bc613a0476abbf5b1ab3/pylint_odoo/misc.py#L261 looks like it's supposed to do that here

**Comment by pedrobaeza** [comment]
OK, thanks for the pointer. @moylop260 your call

**Comment by moylop260** [comment]
pylint and pylint-odoo is ignoring `examples` folder but the error that you face out is of flake8 then this issue should be created and worked from oca/MQT

**Comment by moylop260** [comment]
or maybe we should integrate the flake8 checks to pylint-odoo too in order to centralize it

**Comment by pedrobaeza** [comment]
Well, I think it's too much work to move all the checks to this lib.

**Comment by hbrunn** [comment]
so the right thing to do is to pr ignoring `examples` in mqt, right?

**Comment by hbrunn** [comment]
(it's easy to fix it for my use case, but i ask for directions to make me fix it for the general case. i'm not so well-read on the maintainer's quality scripts)

**Comment by moylop260** [comment]
@hbrunn 
For now you could create a new PR to MQT using [exclude](https://github.com/OCA/maintainer-quality-tools/blob/518efe27b7e4a242c86686e4b9dbb85ee6d610b9/travis/cfg/travis_run_flake8.cfg#L8) parameter from configuration file.

Same case for [other flake8 configuration file](https://github.com/OCA/maintainer-quality-tools/blob/518efe27b7e4a242c86686e4b9dbb85ee6d610b9/travis/cfg/travis_run_flake8__init__.cfg#L7)

**Comment by hbrunn** [comment]
thanks all, it's here: https://github.com/OCA/maintainer-quality-tools/pull/551
