### ISSUE TITLE
[NEW] tests folder imported from module/__init__.py file

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#195]
Sometimes we have packages for tests proposal then we should avoid compile tests folder since that odoo run the tests without an explicit `import tests` from the `module/__init__.py` file.

**Comment by luisg123v** [comment]
@moylop260 
I might be a little bit confused, but isn't this what https://github.com/OCA/pylint-odoo/pull/75 does?

**Comment by moylop260** [comment]
Yes, it is. Thanks!
