### ISSUE TITLE
new check: maintainers key

### ISSUE THREAD

**Issue by sbidoul** [OCA/pylint-odoo#200]
Check that the `maintainers` manifest key, if present, is a list of strings.

**Comment by moylop260** [comment]
Hi @sbidoul 
Is valid this issue yet?

**Comment by moylop260** [comment]
FYI if it is still required you can create a new PR to MQT using the following way:
 - https://github.com/OCA/maintainer-quality-tools/pull/582

Closing since that it is a MQT matter instead of pylint-odoo

**Comment by sbidoul** [comment]
@moylop260 it's not to make the key required, but to check that it is a list of strings if present, so IMO this is still valid for pylint-odoo. What do you think?

**Comment by moylop260** [comment]
I got it
It is similar case to authors but for that case we are checking that it is a string separated by commas

What about using the same way like authors?

Since that could be confuse mixing input for both cases.

What is the rational of this key vs current README?
Who is using this key?

**Comment by sbidoul** [comment]
@moylop260 the maintainer key is documented in `https://odoo-community.org/page/maintainer-role`
