### ISSUE TITLE
[RFC][pylint] Upgrade the pylint version

### ISSUE THREAD

**Issue by rousseldenis** [OCA/pylint-odoo#203]
Hi all,

Is it possible to use the latest version of pylint or at least >=1.8?

Some bugs are resolved. One of them is interesting as the option --ignore of pylint take into account directories (so, module names).

@moylop260

**Comment by rousseldenis** [comment]
Releasing master should be sufficent

**Comment by moylop260** [comment]
I just have created the release: 2.0.0
Thanks
