### ISSUE TITLE
E0401: Unable to import 'odoo' (import-error)

### ISSUE THREAD

**Issue by blaggacao** [OCA/pylint-odoo#204]
I was wondering if this is a valid "issue". I'm sure thought has been spent on this one, but I couldn't find anything about it searching this github repo.

Maybe it would be possible to teach pylint odoo those odoo specific import hooks?

Like to deal with:

- E0401: Unable to import 'odoo' (import-error)
- E0203 (access-member-before-definition), as pylint is not aware of odoo inheritance
- E1133 (not-an-iterable) when trying to iterate over a record-set (might be related to E0401)

I understand not being statically typed, this has it's limits. But maybe it can be pushed further...

**Comment by moylop260** [comment]
Those checks are not created from this project pylint-odoo

You will need read the documentation where those checks are created or disable them.

**Comment by CTimmerman** [comment]
> Those checks are not created from this project pylint-odoo

So it's a generic Pylint import path issue which should be filed at https://github.com/PyCQA/pylint
Apparently it has been and is still open: https://github.com/PyCQA/pylint/issues/3721

**Comment by khouloud01** [comment]
@blaggacao you need to add this line in .pylintrc file :
disable=E0401,C0115,C0116,W0640,R1710,R0913,W0707,C3001,E0203,C0301,W0212
