### ISSUE TITLE
Install pygments to make odoo stop complaining about code in RST?

### ISSUE THREAD

**Issue by simahawk** [OCA/pylint-odoo#211]
![image](https://user-images.githubusercontent.com/347149/44453120-967c4880-a5f8-11e8-86cf-3ce6e52769f5.png)
Would be nice to get rid of this...

In this case related to https://github.com/OCA/web/pull/1022

**Comment by moylop260** [comment]
Hi Simone
Yes, I like it
Could you create an issue for oca/mqt since that this is not a pylint-odoo error, please?
