### ISSUE TITLE
E8103 sql-injection

### ISSUE THREAD

**Issue by CGenie** [OCA/pylint-odoo#219]
Hello,
For the `sql-injection` checker you do check for `execute` and `executemany` methods and disallow variable creation with `%`, `+`, and `format`. However this is a valid way to create an SQL as described in the psycopg2 docs (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#no-sql-injection):
```
>>> cur.execute(                                                # correct
...     SQL("INSERT INTO {} VALUES (%s)").format(Identifier('numbers')),
...     (10,))
```
Notice that the above code contains `execute` and `format` yet is correct and protected against SQL injections. I guess you should check additionally whether the variable is wrapped in `SQL` and `Identifier` and such are used in `format` variables.
I'm currently having an issue with the checker at https://github.com/OCA/hr/pull/478 so it's not a made-up example.
I'm also wondering how did this code
https://github.com/OCA/hr/blob/11.0/hr_holidays_hour/report/hr_holidays_report.py#L50-L52
pass through.

**Comment by moylop260** [comment]
Thanks for identifying another case of this important check

**Comment by CGenie** [comment]
Yeah, for now I'm trying to skip the check via this hack https://github.com/OCA/hr/pull/478/files#diff-e776bfa9f5e992680d0bd15f7ef46facR63 but I guess after you fix this, that can be removed as well.

**Comment by pedrobaeza** [comment]
@moylop260 this has arisen again, can you please check for fixing it?

**Comment by moylop260** [comment]
Hi @pedrobaeza 
Where was it raised again (in order to reproduce it locally)?

**Comment by pedrobaeza** [comment]
https://travis-ci.com/github/OCA/server-tools/jobs/358747391#L381

for https://github.com/OCA/server-tools/pull/1858

**Comment by moylop260** [comment]
Please, check the following fix:
https://github.com/OCA/pylint-odoo/pull/287
