### ISSUE TITLE
Try-except lint check to be disabled in v12

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/pylint-odoo#222]
According commit https://github.com/odoo/odoo/commit/8226aa1db828d2a559c7ffaa31a27ef3e5ba4d0b, we don't need anymore to protect imports on 12.0, so we should remove the guideline for that version and don't make the check on 12.0 branches.

**Comment by pedrobaeza** [comment]
cc @moylop260

**Comment by pedrobaeza** [comment]
Maybe this should go in maintainer-quality-tools...

**Comment by moylop260** [comment]
Thanks for reporting @pedrobaeza 
Could you check the following PR, please?
https://github.com/OCA/pylint-odoo/pull/223
