### ISSUE TITLE
Deprecate pylint_exclude.*cfg from MQT migrating to odoo_check_versions

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#224]
Use `odoo_check_versions` feature like https://github.com/OCA/pylint-odoo/pull/223/files
to migrate MQT exclude configuration files:
 - https://github.com/OCA/maintainer-quality-tools/blob/master/travis/cfg/travis_run_pylint_exclude_61.cfg
 - https://github.com/OCA/maintainer-quality-tools/blob/master/travis/cfg/travis_run_pylint_exclude_70.cfg

And remove the code and configuration files from MQT.

**Comment by pedrobaeza** [comment]
Yeah, this would be cleaner!

**Comment by moylop260** [comment]
Deprecated since that now we are using pre-commit
