### ISSUE TITLE
sql-injection: consider case using `psycopg2.extensions.AsIs`

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#225]
Steps:
1. Create a odoo module using the following sql injection case:
```python
from psycopg2.extensions import AsIs
self.env.cr.execute("SELECT id FROM %s", (AsIs('res_users; DELETE FROM res_users;'),))
```
2. Run pylint enabling sql-injection checker.

Saw:
sql-injection checker is not detected.

Expected:
sql-injection checker detected.

**Comment by pedrobaeza** [comment]
Well, you are ruined the trick for avoiding the check, as there's no other way of for example build the SQL views reports.

**Comment by moylop260** [comment]
We can use a sanitize method like
https://github.com/OCA/server-tools/issues/1426#issuecomment-439411355

Could you share me a code bypassing this check using AsIs?

In order to check if there is a way to skip a special case from the check

**Comment by pedrobaeza** [comment]
This is one example: https://github.com/OCA/crm/blob/c0a0abc5c8b1a9ef17d224bbab768c8f089eddaf/crm_phonecall/report/crm_phonecall_report.py#L134

**Comment by moylop260** [comment]
Using private attributes was fixed here:
 - https://github.com/OCA/pylint-odoo/pull/122/files

I mean, sql-injection is not face out if the variables startswith `_`

I just have created the following PR to test the case:
 - https://github.com/OCA/pylint-odoo/pull/226

**Comment by pedrobaeza** [comment]
Can you try with a variable inside the same scope (not an object variable)?

**Comment by moylop260** [comment]
Done
https://github.com/OCA/pylint-odoo/pull/226/files

**Comment by pedrobaeza** [comment]
Well, I mean if it doesn't count when the variable is in the same scope. Any way, I don't like this, as you are reducing also the possibilities. What about if I want to put this:
```python
"CREATE VIEW %s AS (SELECT %s FROM res_partner)" % (_variable, self.select()))
```

**Comment by moylop260** [comment]
I just have created a talbe of True with all cases using public and private attributes and using with and without underscored variables.

| Use                     | Result             |
|-------------------------|--------------------|
| self._private_attribute | skip sql-injection |
| self.public_attribute   | sql-injection      |
| _variable               | sql-injection      |
| variable                | sql-injection      |

Really, if you use a variable doesn't matter the name.
For OOP the attributes change if it starts with a underscore.
Then, the variables are out of scope for this case.

**Comment by pedrobaeza** [comment]
Then that's why I don't want this new check, because that are valid cases.

**Comment by moylop260** [comment]
I don't get you.

**Comment by pedrobaeza** [comment]
Enabling this check, my cases will be considered error.

**Comment by moylop260** [comment]
Considering `AsIs` in the sql-injection check the new result should be:

| | Use                     | Current Result             | New Result | 
|---|-------------------------|--------------------|------------|
|1 | AsIs(self._private_attribute) | skip sql-injection | skip sql-injection |
|2 | AsIs(self.public_attribute)   | sql-injection      | skip sql-injection |
|3 | AsIs(_variable)               | sql-injection      | skip sql-injection |
|4 | AsIs(variable)                | sql-injection      | skip sql-injection |
|5 | self._private_attribute | skip sql-injection | skip sql-injection |
|6 | self.public_attribute   | sql-injection      | sql-injection      |
|7 | _variable               | sql-injection      | sql-injection      |
|8 | variable                | sql-injection      | sql-injection      |

In this case, you are in the first case, then, your cases won't considered sql-injection error.
In fact, if you remove `AsIs` like case # 5, neither will considered error, since that we are skipping private attributes from https://github.com/OCA/pylint-odoo/pull/226

**Comment by moylop260** [comment]
Closing since it is a valid workaround where the dev needs to be sure it is not a sql-injection
