### ISSUE TITLE
2.0.1 is not backward compatible with 2.0.0.... 

### ISSUE THREAD

**Issue by lmignon** [OCA/pylint-odoo#232]
https://github.com/OCA/pylint-odoo/commit/8dcb1eb9df1e8623680f20f698d58b6e325a67de break the compatibility with the previous version and put all our CI in :red_circle:
Indeed the option has been renamed from `manifest_required_author` to `manifest_required_authors`.  
This kind of change should be released in a major version or the backward compatibility should be preserved.

**Comment by moylop260** [comment]
Please, check https://github.com/OCA/pylint-odoo/pull/233
