### ISSUE TITLE
[RFQ] New check: prefer fields.Datetime.now instead of datetime.datetime.now

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#235]
More info: https://github.com/odoo/odoo/pull/30734

UPDATE:
Jus for odoo 12.0+

**Comment by pedrobaeza** [comment]
Great idea, although only for 12.0+

**Comment by moylop260** [comment]
@antonag32 

Similar for relativedelta where odoo fields.Date* API supports this using `fields.Date.end_of(date_from, "month")` and so on

Only for odoo modules and >=13.0 (or where they are implemented)

**Comment by moylop260** [comment]
I think it could be done adding as deprecated-modules `datetime` and `dateutil` in the pylintrc configuration file

So, closing for now.
