### ISSUE TITLE
New check: unresolved references

### ISSUE THREAD

**Issue by mreficent** [OCA/pylint-odoo#236]
Is it possible to create a new warning check like does pycharm with unresolved references?

![lol](https://user-images.githubusercontent.com/25005517/52426290-f8286480-2afd-11e9-9bcf-0a78e3b765f1.png)

ping: @moylop260

**Comment by moylop260** [comment]
We can’t use checker that requires the full environment to work since that we are not installing depends or cloning repos for lint build checks.

But pylint has a built-in check similar that you can enable for your custom configuration file

**Comment by moylop260** [comment]
Closing because of last comment
