### ISSUE TITLE
New check: api.one on public methods

### ISSUE THREAD

**Issue by mreficent** [OCA/pylint-odoo#237]
I think that we should create a new error check for public methods that use api.one. I know there exists the warning `api-one-deprecated` that shows every time an api.one is used, but it's just a low profile warning. For security reasons, I think it should be considered an error when the method with api.one is public and not private.

I think this check should be easy to implement.

I have seen some PRs like https://github.com/odoo/odoo/pull/30669.

ping: @moylop260

**Comment by yelizariev** [comment]
As I understand, potential dangerous is in publicity of a method, not in ``api.one`` decorator. Do I miss something?

**Comment by moylop260** [comment]
`api.one` will be deprecated
Maybe we should change the api.one from a warning to a error.
But it should be discussed from https://github.com/oca/maintainer-quality-tools
Could you open a new issue please?

**Comment by mreficent** [comment]
Exactly @yelizariev, sorry for my late answer.
