### ISSUE TITLE
Linter should forbid shadowing native objects

### ISSUE THREAD

**Issue by Yajo** [OCA/pylint-odoo#238]
Not sure if this is easy to achieve, or if it belongs here or to core pylint, but let's open the discussion.

[This](https://github.com/OCA/sale-workflow/blob/fdc782bb4495cf5798a0567cf8737132d6417944/sale_order_price_recalculation/models/sale_order.py#L16) should be forbidden: 

```python
dict = line._convert_to_write(line.read()[0])
```

`dict` is a native object and shouldn't be overriden.

**Comment by moylop260** [comment]
Check the following PR: https://github.com/OCA/maintainer-quality-tools/pull/587 please
