### ISSUE TITLE
Pylint broken with connector / connector magento

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/pylint-odoo#243]
Hi since the update of pylint, we face to some weird issue.
Pylint on travis crash in some OCA project and also in Akretion project
Here is an example of trace : https://travis-ci.org/OCA/connector-magento/jobs/395697437#L834

After a deep looking I finally found where the issue was
Connector add the decorator "skip_if" and the syntax seem to break pylint when parsing the code.
https://github.com/OCA/connector-magento/blob/10.0/connector_magento/models/product/common.py#L260

The following code https://github.com/PyCQA/pylint/blame/1.9/pylint/checkers/python3.py#L55
Break here : 

> 
    return isinstance(value, astroid.Instance) and 'dict' in value.basenames

And raise 
> 
    AttributeError: 'FunctionDef' object has no attribute 'basenames'

@guewen @lmignon 

On my side I am going to downgrade to version 1.8.4 for my project.
Sadly I do not have enough time to find an other issue, but at least I hope I will help with this bug report.

**Comment by moylop260** [comment]
Hi @sebastienbeau 
Thanks for your issue.

I checked it and I found that it is raised because of `print-used` pylint core check.
But I'm re-generating a new check from pylint-odoo since that it was deprecated for py3
Then, I will disable it for now for MQT in order to fix it

**Comment by moylop260** [comment]
FYI check the following PR:
 - https://github.com/OCA/maintainer-quality-tools/pull/593
