### ISSUE TITLE
[13.0] Missing api.one or api.multi in copy function

### ISSUE THREAD

**Issue by rven** [OCA/pylint-odoo#257]
W8102: Missing api.one or api.multi in copy function. (copy-wo-api-one)
This warning needs to be removed from the OCA pylint conventions, because Odoo 13 has removed the @api.multi / @api.one / @api.returns decorators

**Comment by moylop260** [comment]
https://github.com/OCA/maintainer-quality-tools/pull/612

**Comment by luisg123v** [comment]
Hi @rven,

I believe this issue may now be closed, as it's been already fixed on https://github.com/OCA/maintainer-quality-tools/commit/50d3a093135e379545c15a58b2a8f5e1e533e19a

**Comment by pedrobaeza** [comment]
Yes, thanks for the followup.
