### ISSUE TITLE
Odoo 13: copy function decorator

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/pylint-odoo#277]
In Odoo 13, an override of the `copy` method has no decorator (no `api.multi`) or has the `api.returns` decorator. The `W8102 Missing api.one or api.multi in copy function. (copy-wo-api-one)` should not be enabled in Odoo 13.

**Comment by luisg123v** [comment]
I'll take care of this.

CC @moylop260, assign it to me if you agree.

**Comment by sbidoul** [comment]
I'd say this kind of issue should be reported in https://github.com/oca/oca-addons-repo-template (>= 13) or OCA/maintainer-quality-tools (<13).

**Comment by moylop260** [comment]
@antonag32

This lint should be deprecated since newer versions are using api.multi by default without explicitly declared and api.one was deprecated
