### ISSUE TITLE
Is black from pre-commit + Odoo code an issue?

### ISSUE THREAD

**Issue by luisg123v** [OCA/pylint-odoo#278]
### Background

OCA projects started using [Black](https://github.com/psf/black) on [their pre-commit files](https://github.com/OCA/oca-github-bot/blob/4b137e25253ab0174028b33a1560c1a940c24e65/.pre-commit-config.yaml#L5)

I'm concern about using black because, given the way Odoo code is written and how strict black is re-writing code, it could lead to undesirable results.

Below is a couple of examples to demonstrate my point:

### Example 1: A simple domain with two terms

Original code:

```
partner = self.env["res.partner"].search([
    ("parent_id", "=", False),
    ("field_two", "=", True),
])
```

The above is converted to:

```
partner = self.env["res.partner"].search(
    [("parent_id", "=", False), ("field_two", "=", True),]
)
```

As you can see, both terms were joined into a single line. This is undesirable IMHO because:
- One term per line is desirable, it's more readable and diffs are clearer when they are modified
- Since the comma that's after the second term was not removed, a lint was introduced:  
  `E231 missing whitespace after ','`

### Example 2: Raising an exception

original code:

```
raise UserError(_(
    "This is an error message taht fits in two lines. It is too long "
    "for one line (exceeds limit), but not too long for three lines"))
```

The above is converted to:

```
raise UserError(
    _(
        "This is an error message taht fits in two lines. It is too long "
        "for one line (exceeds limit), but not too long for three lines"
    )
)
```

The above behavior is undesirable IMHO, because:
- It has an extra indentation level, which is unnecessary. Note that all exceptions will always (or they should) be translatable, so `_()` will always be used
- Again, it introduces a lint, in this case the line is too long:  
  `E501 line too long`

### Final comments

I understand why Black was introduced on the first place, I actually like the rasoning behind that. However, given the above (and other examples I could list), I think that it could give us more inconvenients than advantages. Moreover, it's not something that we could configure to fit our needs (AFAIK and from what I've read), so it's an "all or nothing" or  "take it or leave it".

**Comment by pedrobaeza** [comment]
The point on using black is to not care about all these things. Readability is a subjective thing, and I can agree that sometimes seems worse what black proposes, but the idea behind this is if we need to improve readability, let's push in black for being improved instead of continuing doing manually.

About the trailing comma, this is indeed a side effect of this formatting, but it's not a problem at all, as pre-commit itself warns you and don't let you to continue until you fix it, so it's consistent IMO.

**Comment by sbidoul** [comment]
About Example 1, this has been fixed in the latest version of black, which is now used on 14.0 branches.

**Comment by sbidoul** [comment]
I suggest closing this issue which is not related to pylint-odoo.

**Comment by luisg123v** [comment]
I don't think this issue will mean any change, as the usage of black is already accepted on two versions, so closing.
