### ISSUE TITLE
Some checks seems not to raise

### ISSUE THREAD

**Issue by rousseldenis** [OCA/pylint-odoo#282]
In some situations, some checks seems not to raise. And after adding an extra module (in a PR), the check raises.

Example : https://travis-ci.org/github/shopinvader/odoo-shopinvader/jobs/683813673

The main branch is green. The code of the PR does not change the errored part: https://travis-ci.org/github/shopinvader/odoo-shopinvader/jobs/683813673#L301

The PR code :https://github.com/shopinvader/odoo-shopinvader/pull/631

The culprit code in  base branch (never raised before PR) : https://github.com/shopinvader/odoo-shopinvader/blob/10.0/shopinvader/services/cart.py#L8

**Comment by rousseldenis** [comment]
@moylop260 

@sbidoul

**Comment by moylop260** [comment]
FYI WIP https://github.com/OCA/pylint-odoo/pull/283
