### ISSUE TITLE
Encountering unexpected W7936: Missing external dependency "odoo" from manifest

### ISSUE THREAD

**Issue by TimLai125** [OCA/pylint-odoo#284]
The pre-commit command raises `[W7936(missing-manifest-dependency), ] Missing external dependency "odoo" from manifest. More info: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#external-dependencies` after we update pre-commit to `2.5.1`. 
https://travis-ci.com/github/qrtl/hls-custom/jobs/349626734#L707-L710

The `isort.cfg` already includes `odoo`: https://github.com/qrtl/hls-custom/blob/st2/.isort.cfg
We suspect it maybe cause by the latest pre-commit version affects the pylint behavior and make the checking fails to identify `odoo` 

I am not sure whether it is a related issue which is reported last year: https://github.com/OCA/pylint-odoo/issues/242

**Comment by moylop260** [comment]
Hi @TimLai125 
Thank you for reporting the issue and give us all steps and project to reproduce it.

It was fixed from
 - https://github.com/OCA/pylint-odoo/pull/263

It was released in `pylint-odoo==3.1.0`
 - ![image](https://user-images.githubusercontent.com/6644187/86625296-7b1b4c00-bf8a-11ea-8427-c6500677c569.png)

Last `pylint-odoo==3.3.1`:
 - https://pypi.org/project/pylint-odoo/

You are using an old `pylint-odoo==3.0.3`:
 - https://github.com/qrtl/hls-custom/blob/c1fb428eb5cd101ccbeb137d8315fd8cc166b4f7/.pre-commit-config.yaml#L117

Could you update your pylint-odoo version and check it again, please?

**Comment by luisg123v** [comment]
Hi @TimLai125,

Did you test the solution commented by @moylop260?

**Comment by TimLai125** [comment]
@moylop260  Thank you for the suggestion, but we could not reproduce the issue now. We will update our pylint-odoo version anyways to avoid the same issue happens again. I am closing this issue for now.
