### ISSUE TITLE
Odoo 14 compatibility 

### ISSUE THREAD

**Issue by c-engelhardt-ecoservice** [OCA/pylint-odoo#311]
Check `manifest-version-format` currently not compatible with Odoo 14 as not included in `misc.DFTL_VALID_ODOO_VERSIONS`

**Comment by moylop260** [comment]
@fernandahf 

Could you add the new 14.0 here, please?

 - https://github.com/OCA/pylint-odoo/blob/88db7a521d96e579c6834a9b3596ba5d89d48d32/pylint_odoo/misc.py#L27

@c-engelhardt-ecoservice 

 - You can run pylint using: `--valid-odoo-versions="14\.0"`
