### ISSUE TITLE
AttributeError raised when running odoo_pylint checks

### ISSUE THREAD

**Issue by jlopezg** [OCA/pylint-odoo#318]
Got this error after #310 

> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/bin/pylint", line 8, in <module>
>     sys.exit(run_pylint())
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/__init__.py", line 22, in run_pylint
>     PylintRun(sys.argv[1:])
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
>     linter.check(args)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
>     self.get_ast, self._iterate_file_descrs(files_or_modules)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
>     self._check_file(get_ast, check_astroid_module, name, filepath, modname)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
>     check_astroid_module(ast_node)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
>     ast_node, walker, rawcheckers, tokencheckers
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
>     walker.walk(ast_node)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
>     self.walk(child)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
>     callback(astroid)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 471, in visit_import
>     self.check_folder_test_imported(node)
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pylint_odoo/checkers/modules_odoo.py", line 371, in check_folder_test_imported
>     or "tests" in node.modname)):
> AttributeError: 'Import' object has no attribute 'modname'

**Comment by jlopezg** [comment]
Hi @fernandahf 
Can you have a check of this, please?

**Comment by moylop260** [comment]
It will be fixed in the following PR:
 - https://github.com/OCA/pylint-odoo/pull/315

**Comment by jlopezg** [comment]
Thanks @moylop260
