### ISSUE TITLE
Why is pylint-odoo reports "Deprecated key "description" in manifest file"?

### ISSUE THREAD

**Issue by tmotyl** [OCA/pylint-odoo#326]

**Comment by pedrobaeza** [comment]
Because description is got from README.rst file.

**Comment by tmotyl** [comment]
can you elaborate? The field is present in the officeial reference:
https://www.odoo.com/documentation/14.0/reference/module.html?highlight=manifest

**Comment by pedrobaeza** [comment]
It's better to put contents in that file than having them mixed with the rest of the manifest, without total control of the format or line length limitation, and it's a guideline in OCA, which is the main target for pylint-odoo. If you don't want it, disable that check in your config for your custom repository.

**Comment by tmotyl** [comment]
all right, thanks
