### ISSUE TITLE
Document how to configure misc.DFTL_MANIFEST_VERSION_FORMAT, / manifest_version_format in pylintrc

### ISSUE THREAD

**Issue by tmotyl** [OCA/pylint-odoo#327]
It would be great if it was documented how to configure custom regex for checking module version instead of default DFTL_MANIFEST_VERSION_FORMAT
through .pylintrc

I've tried setting manifest_version_format, but it didn't help.

**Comment by jgrandguillaume** [comment]
Hi @tmotyl 

Thanks for reporting here. I don't know how to help here, but may be @moylop260 can give a hands ?

Regards,

Joël
