### ISSUE TITLE
manifest_version_format option was ignored

### ISSUE THREAD

**Issue by voronind** [OCA/pylint-odoo#337]
```console
$ pylint --load-plugins=pylint_odoo --long-help | grep manifest_version_format -A3
--manifest_version_format=<string>
                        Regex to check version format in manifest file. Use
                        "{valid_odoo_versions}" to check the parameter of
                        "valid_odoo_versions" [current: ^12$]
```
In fact we can not custom this option cause code uses just default DFTL_MANIFEST_VERSION_FORMAT variable.  
We need to custom this option cause `pylint-odoo` is used not for OCA modules only.

**Comment by moylop260** [comment]
Could you help us with the steps to reproduce it, please?

**Comment by voronind** [comment]
> Could you help us with the steps to reproduce it, please?

Add to `.pylintrc` option with any value. For example  
```
[ODOOLINT]
manifest_version_format=({valid_odoo_versions})\.\d+(?:\.\d+)?$
```

If version format doesn't confirm default we get error:
```
addon-name/__manifest__.py:1:0: C8106: Wrong Version Format "11.0.1" in manifest file. Regex to match: "(11\.0)\.\d+\.\d+\.\d+$" (manifest-version-format)
```

I saw sources. There is no option using. It was worked well before.

**Comment by voronind** [comment]
:+1:
