### ISSUE TITLE
Automatic refactoring - code migration (AST/CST)

### ISSUE THREAD

**Issue by tmotyl** [OCA/pylint-odoo#340]
Did any of you experimented with tools for automatic code migration/refactorings for the rules/issues detected by pylint-odoo?

I saw there are already some nice tools which provides API for code manipulation like:
https://github.com/isidentical/refactor 
https://github.com/davidhalter/parso
https://github.com/Instagram/LibCST
https://github.com/Instagram/Fixit 

This approach could also be useful for openupgrade project to automatically migrate code to new odoo API.
And saves tons of hours on manual refactoring.

I saw this approach being a great success in the PHP world - https://github.com/rectorphp/rector where the tool has hundreds of rules (generic ones, and framework specific).

I would be interesting in joining forces in working on such a tool for odoo, or/and sponsoring the development.

**Comment by moylop260** [comment]
We are using black, prettier and eslint with pre-commit to auto-fix linters

You can check nee branches 14.0 in many OCA projects

pylint and pylint-odoo doesn't have a way to auto-fix but report

**Comment by tmotyl** [comment]
Hi I know that currently odoo-pylint is not able to auto fix issues. Thats why I opened this issue/request :)
