### ISSUE TITLE
[PERF] use is_message_enabled for all lints

### ISSUE THREAD

**Issue by fernandahf** [OCA/pylint-odoo#372]
Currently, there are some lints that are not using the following validation:

https://github.com/OCA/pylint-odoo/blob/5c15bca5fa12f3eaef54e03a1d8718150f6f2d5a/pylint_odoo/checkers/no_modules.py#L872

That generates all code in those lints, even if they are disabled, are checked.

Example: 

https://github.com/OCA/pylint-odoo/blob/5c15bca5fa12f3eaef54e03a1d8718150f6f2d5a/pylint_odoo/checkers/no_modules.py#L593-L751

**Comment by antonag32** [comment]
Working on the issue, however before fixing any code I am thinking of ways we can objectively measure the code quality, or performance loss/increase. 

Right now it seems there are to ways to be sure the checks won't run if the message is enabled, one of them is using `@utils.check_messages` or `@utils.only_required_for_messages`. The other one is with the checks proposed in the OP:
`if self.linter.is_message_enabled('copy-wo-api-one'): `

 The only problem with `@utils.only_required_for_messages` is that it only works when one message is used, when multiple messages are included as arguments, the method can be called if one of them is enabled, while all the others are disabled, causing the issue we are trying to fix.

The first method of devising the code quality and finding all messages that are added without checking is by statical analysis of the code, this will be done with a pylint checker (writing a pylint checker to check pylint checkers :sunglasses: ) currently developed at https://github.com/antonag32/lilint.

**Comment by antonag32** [comment]
Apparently I overthought too much too fast, lilint will stay for posterity since it was too young to die but there are more important lints to write, so I will just do this by hand and hope to get as much `add_message` nodes as possible.
