### ISSUE TITLE
dangerous-qweb-replace-wo-priority not working

### ISSUE THREAD

**Issue by mileo** [OCA/pylint-odoo#403]
Hi,

We are trying to use the dangerous-qweb-replace-wo-priority at l10n-brazil without success:

https://github.com/OCA/l10n-brazil/pull/2185/files

https://github.com/OCA/l10n-brazil/actions/runs/3303254570/jobs/5450967762#step:7:72

![image](https://user-images.githubusercontent.com/1975978/197339276-95af4b7d-626e-4c08-ba7a-d37c897a4294.png)

![image](https://user-images.githubusercontent.com/1975978/197339085-340023cf-24d9-4a4a-9024-a86829a9e678.png)

![image](https://user-images.githubusercontent.com/1975978/197339256-bfe1916a-c98a-48f5-98a7-98f0a248d691.png)

cc: @rvalyi @renatonlima @marcelsavegnago

**Comment by moylop260** [comment]
Hi @mileo 

You can change the minimal value needed too using parameters

The default value is 99

Try using 100 instead of 60 if you don't like change the parameter

**Comment by mileo** [comment]
> Hi @mileo
> 
> You can change the minimal value needed too using parameters
> 
> The default value is 99
> 
> Try using 100 instead of 60 if you don't like change the parameter

I can't believe I didn't see the message properly lol. Thanks!
