### ISSUE TITLE
translation-required on every exceptions

### ISSUE THREAD

**Issue by guewen** [OCA/pylint-odoo#41]
I like to distinguish 2 types of errors:

* User errors, which concern the user and are more or less nicely displayed to her (`UserError`, `ValidationError`, ...)
* Exception errors which concern the developers and are either logged, either caught by a `try: except:` reraising a `UserError`, either left as a connector job error, ...

While the first type of errors is surely translated, I dislike to translate the exception errors, that's a pain for the developers to search for translated errors.

Actual:

The `translation-required` lint actually requires every exception raised to be translated.

https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/checkers/no_modules.py#L443-L460

Expected:

The `translation-required` lint requires only the Odoo Exceptions (`UserError`, `ValidationError`) raised to be translated.

**Comment by moylop260** [comment]
I'll working this issue

**Comment by moylop260** [comment]
Fix https://github.com/OCA/pylint-odoo/pull/43
