### ISSUE TITLE
[REF] resource-not-exist: Consider the manifest's key `images`

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#447]
images has a local path to image file so we need to consider it from the check resource-not-exists

**Comment by voronind** [comment]
AFAIK images has non-local path in common case

**Comment by moylop260** [comment]
Could you share a module using a non-local path, please?

FYI I just ran locally the following to get all the non-local path:
`rgrep "images" --include=__manifest__.py |grep http |wc -l`
Result: 0

Local paths:
`rgrep "images" --include=__manifest__.py | wc -l`
375

Please, share more details
