### ISSUE TITLE
Don't pin dependencies so strictly

### ISSUE THREAD

**Issue by voronind** [OCA/pylint-odoo#457]
Dependencies pinned too strictly. It disturb to use pylint-odoo with other Python and lib versions. Libraries such as pylint-odoo need to pin dependencies more wildly. 

Now it's
```txt
pylint-plugin-utils==0.7
pylint==2.15.*
validators==0.20.0
```

**Comment by moylop260** [comment]
Hi @voronind 

Could you create a Pull Request with your proposal, please?

My only concern is that this project is very sensible since all the CI of OCA repositories depend on this package and there are very few people creating fixes

So, if there is a new incompatible release, I will need to fix it ASAP

In fact, you are creating an issue by waiting for something else to create the Pull Request to fix it

So, this issue double-confirm that

Imagine at 3:00am (my timezone) pylint releases a new version incompatible with pylint-odoo and it needs to be updated to be able to work meanwhile, all the CI will be red

But maybe I could be wrong

**Comment by voronind** [comment]
> Could you create a Pull Request with your proposal, please?

No. It's way to manage of dependencies.

Projects must lock all dependencies to be reproducible. Libraries must declare dependencies as wide as possible to be compatible with other libraries.
For example, pylint-plugin-utils declare dependency widely: pylint>=1.7. If pylint-plugin-utils pin version of pylint to 2.10.0 we couldn't use it with pylint-odoo.

Pylint-odoo is just one of pylint plugins. If all pylint plugins will pin pylint version too strictky we can not use it together.

> In fact, you are creating an issue by waiting for something else to create the Pull Request to fix it

Yes, I do

> Imagine at 3:00am (my timezone) pylint releases a new version incompatible with pylint-odoo and it needs to be updated to be able to work meanwhile, all the CI will be red

CI pipelines must pin pylint version.

**Comment by voronind** [comment]
I understood. It is consequences of using pylint-odoo as a pre-commit hook. Pylint must be used as pre-commit hook. Why is plugin replacing base library? IMHO adding pre-commit hook was error and this way has more disadvantages than advantages.

**Comment by moylop260** [comment]
Sorry, I didn't get you

Could you share the steps to reproduce the issue and more details related to the error you are facing?

**Comment by voronind** [comment]
It's not error.

I can not use last pylint-odoo versions cause, for example
1. I use old Python version. Only old versions of pylint can be installed. (<=2.14)
2. I use pylint-other-plugin. It requires old version of pylint (<=2.14)

My .pre-commit-config.yaml. 
```yaml
    ...
    -   repo: https://github.com/PyCQA/pylint
        rev: v2.15.9
        hooks:
            -   id: pylint
                additional_dependencies:
                    - pylint-odoo==8.0.17
                    - pylint-other-plugin==1.0
```

**Comment by moylop260** [comment]
I just used your pre-commit configuration:

```yaml
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.9
    hooks:
        - id: pylint
          additional_dependencies:
            - pylint-odoo==8.0.17
            - pylint-other-plugin==1.0
```

And ran the following command:
 - `pre-commit run pylint --all`

The result was:

```txt
[INFO] Installing environment for https://github.com/PyCQA/pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/moylop260/.cache/pre-commit/repole9opeva/py_env-python3/bin/python', '-mpip', 'install', '.', 'pylint-odoo==8.0.17', 'pylint-other-plugin==1.0')
return code: 1
stdout:
    Processing /Users/moylop260/.cache/pre-commit/repole9opeva
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting pylint-odoo==8.0.17
      Downloading pylint_odoo-8.0.17-py3-none-any.whl (26 kB)

stderr:
    ERROR: Could not find a version that satisfies the requirement pylint-other-plugin==1.0 (from versions: none)
    ERROR: No matching distribution found for pylint-other-plugin==1.0

Check the log at /Users/moylop260/.cache/pre-commit/pre-commit.log
```

No exists the following package:
 - https://pypi.org/project/pylint-other-plugin/


Could you share the real pre-commit file and the command executed, please?

And share more details of the real issue, please

```txt
Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link:
```

**Comment by voronind** [comment]
I give up
