### ISSUE TITLE
Wrong hook example in README

### ISSUE THREAD

**Issue by antonag32** [OCA/pylint-odoo#462]
The suggested usage for this repository as a pre-commit hook is wrong. It suggests using `id: pylint`:
https://github.com/OCA/pylint-odoo/blob/c1335a0db590efd0390941effade29227d6b00d8/README.md?plain=1#L83-L93

But the only id that exists is `pylint_odoo`:
https://github.com/OCA/pylint-odoo/blob/c1335a0db590efd0390941effade29227d6b00d8/.pre-commit-hooks.yaml#L1-L6

**Comment by moylop260** [comment]
You are right!

In fact, our CI lint tool is using the correct way:
 - https://github.com/Vauxoo/pre-commit-vauxoo/blob/34489f02585922b6f0c9c16568c9a185c4370ffa/src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml#L36-L39

**Comment by antonag32** [comment]
Yes, I noticed because I was going to point a user in #460 to the README but realized it was wrong hehe.
