### ISSUE TITLE
"Missing newline at end of file" check unwanted in some cases

### ISSUE THREAD

**Issue by yvaucher** [OCA/pylint-odoo#47]
Hello,

Sometime we have sample files to test import. Those file are integrated in the module and saved as they were generated. We don't want to alter them at all as they are reference file for test purpose.

Thus we should disable this check:

    l10n_ch_account_statement_base_import/init.py:1: [W7908(missing-newline-extrafiles), ] data/UBS_export.csv Missing newline

Or provide a folder in module structure that isn't checked as it isn't odoo data but data to be processed by the module.

Or maybe we only want to check the files that are listed in the `__openerp__.py`

While we are searching for a solution I recommend to disable this check.

Example: https://travis-ci.org/OCA/l10n-switzerland/jobs/143363706

**Comment by moylop260** [comment]
@OCA/core-maintainers What do you think about?

**Comment by dreispt** [comment]
Would having the check only on py and xml files do?

**Comment by gurneyalex** [comment]
I honestly don't care about the presence or absence of a new line at the end of any file in an Odoo module. Enforcing it brings nothing to the readability of the code (or lack thereof), and is only a hassle to contributors. 

I'm *not* in favor of having a pylint check mandating this -> I'm :+1: on this issue.

**Comment by moylop260** [comment]
For record, the reason of the check:

- The reviewers request add a newline at end of file. (You can find them with [search newline comments from oca](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+user%3AOCA+newline+))
 - https://github.com/OCA/web/pull/389#discussion_r71902501
 - https://github.com/OCA/social/pull/74#discussion_r68369033
 - https://github.com/OCA/l10n-italy/pull/208#discussion_r56490900
 - https://github.com/OCA/l10n-italy/pull/138#discussion_r47076461
 - https://github.com/OCA/partner-contact/pull/201#discussion_r44780362
 - https://github.com/OCA/l10n-switzerland/pull/221#issuecomment-196701210
 - https://github.com/OCA/vertical-medical/pull/39#discussion_r40938313

- The history: https://robots.thoughtbot.com/no-newline-at-end-of-file

- Github show:
![without newline](https://cloud.githubusercontent.com/assets/6644187/14660615/8f41a4ee-066c-11e6-9eb9-6f9e9e56f7b2.png)

- If you have a editor with a configuration to auto-add a newline then you will see a dummy change of newline in all files edited.
Very similar to our [idioms](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#idioms) guideline
```md
- When making a comma separated list, dict, tuple, ... with one element per line, 
 **append a comma** to the last element.
 This makes it so the next element added only changes one line in the changeset 
 instead of changing the last element to simply add a comma.
```


But the issue LGTM to add a improvement to skip it for some files.
In the case commented in this issue the file is a sample (It's not a real module file)
Maybe using a `examples` folder in our modules, I saw this folder in many projects for this proposal:
 - [github projects examples in:path](https://github.com/search?utf8=%E2%9C%93&q=examples+in%3Apath&type=Code&ref=searchresults)

**Comment by StefanRijnhart** [comment]
Thanks @moylop260 for documenting the case for this check. Would it be possible to implement one of the suggested solutions from the OP, checking python files + data files referenced in the manifest file?

**Comment by moylop260** [comment]
@StefanRijnhart 
Yes, we can use the manifest but we don't have the following files: `po, js, mako...`

Maybe, if we use a `examples` folder to ignore additional checks could be a good idea.

**Comment by moylop260** [comment]
FYI fix https://github.com/OCA/pylint-odoo/pull/63
