### ISSUE TITLE
Why do you pin pylint to 1.4.4?

### ISSUE THREAD

**Issue by agb80** [OCA/pylint-odoo#58]
Just like the title said, is there any specific reason you are pinning pylint to 1.4.4 version or can I make a PR to allow use the latest available pylint version?

**Comment by moylop260** [comment]
You can create a PR with the latest stable version.
FYI we have freeze the specific version because we had issues in the past with changes of version.
If the tests run fine, then we can merge it.
If not you could fix it.

**Comment by agb80** [comment]
Will do it, thank you!

**Comment by moylop260** [comment]
I have created a new lint from [pylint](https://github.com/pycqa/pylint) for Cyclomatic complexity https://github.com/PyCQA/pylint/pull/877 and was released on latest version
Then we are waiting your PR to update pylint-odoo and enable this check for MQT after...

**Comment by moylop260** [comment]
@agb80 
Tell us if you will can help us with this matter, please.
I want to work on this but I'm stopped by your promise of help us in order to avoid duplicate work

**Comment by agb80** [comment]
I'm going to be really busy this days and have not being able to work into this issue until weekend. If you think that is better that you work on this in order to get it done quickly please go ahead.

If you don't have done any work on this for next Friday I will take it for sure.
