### ISSUE TITLE
crash on OCA/sale-workflow

### ISSUE THREAD

**Issue by gurneyalex** [OCA/pylint-odoo#60]
The PR https://github.com/OCA/sale-workflow/pull/316  on OCA/sale-workflow caused a pylint crash: https://travis-ci.org/OCA/sale-workflow/jobs/144136646#L464

      File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/pylint_odoo/checkers/no_modules.py", line 476, in visit_raise
    
        func_name = node.exc.func.name
    
    AttributeError: 'Getattr' object has no attribute 'name'

**Comment by moylop260** [comment]
Duplicated https://github.com/OCA/pylint-odoo/issues/46 and fixed https://github.com/OCA/pylint-odoo/pull/48

The build is too old
![22days](https://cloud.githubusercontent.com/assets/6644187/17361025/ebb0f2f6-5933-11e6-8150-357d49108dcd.png)

I rebuilt and now is green
<img width="1063" alt="screen shot 2016-08-03 at 4 38 10 am" src="https://cloud.githubusercontent.com/assets/6644187/17361067/1f20fda2-5934-11e6-80c2-709934369719.png">

https://travis-ci.org/OCA/sale-workflow/jobs/144136646
