### ISSUE TITLE
Is there any way to locally disable file-not-used?

### ISSUE THREAD

**Issue by agb80** [OCA/pylint-odoo#71]
We have a really big data file, more than 9million records and is a must that we upload the information with our module. 

Upload all that data into a database using the data field on manifiest takes ages, that's why we are uploading the information using plain queries. Is there any way to locally disable ```file-not-used``` only for that specific module?

EDIT: Forgot to said that already tried using ```# pylint: disable=file-not-used``` at the ```__openerp__.py``` file with no effect

**Comment by pedrobaeza** [comment]
Put it on the examples folder or create an specific pylint config file ignoring it.

**Comment by agb80** [comment]
Thanks for your suggestion @pedrobaeza, the examples files is a good option.
