### ISSUE TITLE
Import in test files must not be protected

### ISSUE THREAD

**Issue by lmignon** [OCA/pylint-odoo#74]
If a test file is run, the required libs must be installed. Therefore we must not protect the import since these files are loaded by odoo only when running tests

https://travis-ci.org/acsone/reporting-engine/jobs/167070681#L293

**Comment by moylop260** [comment]
Thanks @lmignon 
Could you add the explicit rule for tests in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#external-dependencies?

**Comment by lmignon** [comment]
@moylop260 here it's https://github.com/OCA/maintainer-tools/pull/230

**Comment by pedrobaeza** [comment]
Closing as there's a PR
