### ISSUE TITLE
I can not have demo and data with the same xml id because the next error is displayed:  [W7902(duplicate-xml-record-id), ]  Duplicate xml record id 

### ISSUE THREAD

**Issue by yaniaular** [OCA/pylint-odoo#83]
**Error**

I can not have demo and data record with a same xml id because the next error is displayed: 

``` python
data/res_company.xml:4: [W7902(duplicate-xml-record-id), ]  Duplicate xml record id "base.main_company.noupdate0" in demo/res_company.xml
```

**Steps to reproduce the error:**
1. I have two files: data/res_company.xml and demo/res_company.xml
2. The main company is edited in both files: 

**data/res_company.xml** 

``` xml
<record id="base.main_company" model="res.company">
     <field name="new_field_id" ref="module.reference_example_1"/>
</record>
```

**demo/res_company.xml**

``` xml
<record id="base.main_company" model="res.company">
     <field name="example_field">300</field>
</record>
```

With this scene, the next error is displayed:

``` python
data/res_company.xml:4: [W7902(duplicate-xml-record-id), ]  Duplicate xml record id "base.main_company.noupdate0" in demo/res_company.xml
```

**Conclusion**

 I think I can have data and demo with the same xml_id, it is valid.

I think this is a bug

**Comment by dreispt** [comment]
Why would you need that?

**Comment by guewen** [comment]
I think I had the same use case. You want to update or create data at the installation of the addon, but you want to configure a field with a particular value for the demo.

**Comment by moylop260** [comment]
FYI fixed from https://github.com/OCA/pylint-odoo/issues/89 your feedback is welcome
