### ISSUE TITLE
Crash with compute=None

### ISSUE THREAD

**Issue by adrienpeiffer** [OCA/pylint-odoo#88]
Hi,

I have a case in which I want to change the behavior of a computed field to do a field that is not computed. So, I put ```compute=None``` and that works well.

Unfortunately this causes a problem with odoo-pylint like this

```
pylint_odoo/checkers/no_modules.py", line 295, in visit_call
not argument.value.value.startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'
```

@moylop260 Do you have any comments about this one ?

Thanks,

Adrien

**Comment by moylop260** [comment]
Thanks for reporting

**Comment by moylop260** [comment]
FYI fixing https://github.com/OCA/pylint-odoo/pull/90
Your feedback is welcome
